-- Correctie JiveX fouten verslagne bij patiënt 13642850 op 2015-06-15

/****** [UITSLAG5_PA_VERR]  ******/
SELECT [ONDERZNR]
      ,[CODE]
      ,[VOLGNR]
      ,[VERSLAG]
      ,[STATUS]
      ,[URL]
  FROM [HIX_ACCEPTATIE].[dbo].[UITSLAG5_PA_VERR]
  WHERE [ONDERZNR] IN (
	SELECT
		[ONDERZNR]
	FROM [HIX_ACCEPTATIE].[dbo].[UITSLAG5_PA_OND]
	WHERE [PATIENTNR] LIKE '13642850' AND [MONSTERDAT] = '2015-06-15' AND [MONSTRTIJD] = '0940' -- AND [STATUS] != 'X'
  ) 

  UPDATE [HIX_ACCEPTATIE].[dbo].[UITSLAG5_PA_VERR]
  SET [STATUS] = 'X'
  WHERE [ONDERZNR] IN (
	SELECT
		[ONDERZNR]
	FROM [HIX_ACCEPTATIE].[dbo].[UITSLAG5_PA_OND]
	WHERE [PATIENTNR] LIKE '13642850' AND [MONSTERDAT] = '2015-06-15' AND [MONSTRTIJD] = '0940' AND [STATUS] != 'X'
  ) 


/****** [UITSLAG5_PA_OND]  ******/
SELECT [ONDERZNR]
      ,[PATIENTNR]
      ,[MONSTERDAT]
      ,[VERSLAGDAT]
      ,[AANVRAGER]
      ,[STATUS]
      ,[OMSCRHIJV]
      ,[UITVOERDER]
      ,[MUTDAT]
      ,[MUTTIJD]
      ,[ORDERNR]
      ,[MONSTRTIJD]
      ,[VERSLGTIJD]
      ,[MATERIAAL]
      ,[URL]
      ,[ORDERCOMORDERNR]
      ,[LOCATIONCODE]
      ,[ASSESSEDBYID]
  FROM [HIX_ACCEPTATIE].[dbo].[UITSLAG5_PA_OND]
  WHERE [PATIENTNR] LIKE '13642850' AND [MONSTERDAT] = '2015-06-15' AND [MONSTRTIJD] = '0940' AND [STATUS] != 'X'

  UPDATE [HIX_ACCEPTATIE].[dbo].[UITSLAG5_PA_OND]
  SET [STATUS] = 'X'
  WHERE [PATIENTNR] LIKE '13642850' AND [MONSTERDAT] = '2015-06-15' AND [MONSTRTIJD] = '0940' AND [STATUS] != 'X'