USE HIX_PRODUCTIE;
GO

SELECT TOP (100)
       VERSION AS [HiX Versie],
       LATEST_HF AS Hotfix,
       (SELECT INDATUM + CAST(INTIJD AS DATETIME)) AS InstallatieDatum
FROM dbo.ZISCON_LOGSESSI WITH (READUNCOMMITTED)
WHERE (APPLICATIE = 'CHIPSOFT.DATABAS' OR APPLICATIE = 'CS-HIX UPGRADE')
      AND YEAR (INDATUM) = 2021
ORDER BY INDATUM DESC,
         INTIJD DESC;