SELECT CODE,
       ABSRTCODE,
       ABONNEENR,
       EDIVERSIE,
       ARTSCODE,
       OPNAME,
       ONTSLAG,
       MUTATIE,
       LAB,
       RONTGEN,
       BRIEVEN,
       WAARNRETBER,
       VERVALLEN,
       EMAILPOP,
       EMAILSMTP
FROM HiX_Acc.dbo.EDIFACT_EDIABON
WHERE ABONNEENR LIKE '9999%';