CREATE DATABASE MyFileTable
WITH FILESTREAM (NON_TRANSACTED_ACCESS=FULL, DIRECTORY_NAME=N'FileTableDir');
GO

ALTER DATABASE MyFileTable ADD FILEGROUP FileTableFG CONTAINS FILESTREAM;
GO

ALTER DATABASE MyFileTable
ADD FILE (NAME = 'FileTable_File', FILENAME = 'D:\MSSQL\Data\FileTable')
TO FILEGROUP FileTableFG;
GO

USE MyFileTable;
GO

CREATE TABLE documents AS FILETABLE
WITH (FILETABLE_DIRECTORY = 'FileTableDir');

