
SELECT [VALUE]
FROM CONFIG_INSTVARS 
WHERE [NAAM] = 'DWH_AS' AND [INSTTYPE] = 'G'

SELECT [VALUE]
FROM CONFIG_INSTVARS 
WHERE [NAAM] = 'DWH_CATALOG' AND [INSTTYPE] = 'G'

SELECT [VALUE]
FROM CONFIG_INSTVARS 
WHERE [NAAM] = 'DWH_REPSRV' AND [INSTTYPE] = 'G'

SELECT [VALUE]
FROM CONFIG_INSTVARS 
WHERE [NAAM] = 'DWH_UDL' AND [INSTTYPE] = 'G'