-- ISOFT aanlevering
SELECT UITVOERDER, COUNT(*)  AS AANTAL
FROM CS_ConversieAanlevering.dbo.AGENDA_AFSPRAAK a
 LEFT OUTER JOIN FZR_aanlevering.dbo.MAPPING_FZR_ARTS b
 ON a.UITVOERDER = b.OLD COLLATE DATABASE_DEFAULT
WHERE b.OLD is null
GROUP BY UITVOERDER


SELECT AANVRAGER, COUNT(*)  AS AANTAL
FROM CS_ConversieAanlevering.dbo.AGENDA_AFSPRAAK a
 LEFT OUTER JOIN FZR_aanlevering.dbo.MAPPING_FZR_ARTS b
 ON a.AANVRAGER = b.OLD COLLATE DATABASE_DEFAULT
WHERE b.OLD is null
GROUP BY AANVRAGER

--PARF aanlevering


SELECT UITVOERDER, COUNT(*)  AS AANTAL
FROM CS_ConversieAanlevering_PARF.dbo.AGENDA_AFSPRAAK a
 LEFT OUTER JOIN FZR_aanlevering.dbo.MAPPING_FZR_ARTS b
 ON a.UITVOERDER = b.OLD COLLATE DATABASE_DEFAULT
WHERE b.OLD is null
GROUP BY UITVOERDER


SELECT AANVRAGER, COUNT(*)  AS AANTAL
FROM CS_ConversieAanlevering_PARF.dbo.AGENDA_AFSPRAAK a
 LEFT OUTER JOIN FZR_aanlevering.dbo.MAPPING_FZR_ARTS b
 ON a.AANVRAGER = b.OLD COLLATE DATABASE_DEFAULT
WHERE b.OLD is null
GROUP BY AANVRAGER