SELECT * FROM [CS_MAPPING].[dbo].[MERGE_MAPPING_FZR_CSZISLIB_ARTS_ARTSCODE];
SELECT * FROM [GPHIXSQL01.ZKH.LOCAL].[EZIS_PREPRODUCTIE].[dbo].[CSZISLIB_ARTS];
SELECT FZR.[OLD] AS OUD_FZR, LZB.[OLD] AS OUD_LZB, A.*
  FROM [GPHIXSQL01.ZKH.LOCAL].[HIX_PRODUCTIE].[dbo].[CSZISLIB_ARTS] A
  LEFT OUTER JOIN [CS_MAPPING].[dbo].[MERGE_MAPPING_FZR_CSZISLIB_ARTS_ARTSCODE] FZR
  ON A.ARTSCODE = FZR.[NEW]
  LEFT OUTER JOIN [CS_MAPPING].[dbo].[MERGE_MAPPING_LZB_CSZISLIB_ARTS_ARTSCODE] LZB
  ON A.ARTSCODE = LZB.[NEW]
  WHERE A.ARTSTYPE = 'I' AND a.VERVALLEN = 0
  
  
  
SELECT FZR.[OLD] AS OUD_FZR, LZB.[OLD] AS OUD_LZB, A.*
  FROM [GPHIXSQL01.ZKH.LOCAL].[EZIS_PREPRODUCTIE].[dbo].[CSZISLIB_TBI] A
  LEFT OUTER JOIN [FZR_aanlevering].[dbo].MAPPING_FZR_TBI FZR
  ON A.TBICODE = FZR.[NEW] collate database_default
  LEFT OUTER JOIN [FZR_aanlevering].[dbo].MAPPING_LZB_TBI LZB
  ON A.TBICODE = LZB.[NEW] collate database_default
  WHERE A.TBITYPE = 'V'
  ORDER BY FZR.[OLD] ASC
  
SELECT FZR.[OLD] AS OUD_FZR, A.TBICODE
  FROM [GPHIXSQL01.ZKH.LOCAL].[HIX_PRODUCTIE].[dbo].[CSZISLIB_TBI] A
  LEFT OUTER JOIN [FZR_aanlevering].[dbo].MAPPING_FZR_TBI FZR
  ON A.TBICODE = FZR.[NEW] collate database_default
  WHERE A.TBITYPE = 'V' AND FZR.[OLD] IS NOT NULL
  ORDER BY FZR.[OLD] ASC
  
SELECT FZR.[OLD] AS OUD_LZB, A.TBICODE
  FROM [GPHIXSQL01.ZKH.LOCAL].[HIX_PRODUCTIE].[dbo].[CSZISLIB_TBI] A
  LEFT OUTER JOIN [FZR_aanlevering].[dbo].MAPPING_LZB_TBI FZR
  ON A.TBICODE = FZR.[NEW] collate database_default
  WHERE A.TBITYPE = 'V' AND FZR.[OLD] IS NOT NULL
  ORDER BY FZR.[OLD] ASC
  
 

  
SELECT FZR.[OLD] AS OUD_FZR, A.ARTSCODE
  FROM [GPHIXSQL01.ZKH.LOCAL].[HIX_PRODUCTIE].[dbo].[CSZISLIB_ARTS] A
  LEFT OUTER JOIN [FZR_aanlevering].[dbo].MAPPING_FZR_ARTS FZR
  ON A.ARTSCODE = FZR.[NEW] collate database_default
  WHERE FZR.[OLD] IS NOT NULL
  ORDER BY FZR.[OLD] ASC
  
SELECT LZB.[OLD] AS OUD_LZB, A.ARTSCODE
  FROM [GPHIXSQL01.ZKH.LOCAL].[HIX_PRODUCTIE].[dbo].[CSZISLIB_ARTS] A
  LEFT OUTER JOIN [FZR_aanlevering].[dbo].MAPPING_LZB_ARTS LZB
  ON A.ARTSCODE = LZB.[NEW] collate database_default
  WHERE LZB.[OLD] IS NOT NULL
  ORDER BY LZB.[OLD] ASC

